### ISSUE TITLE
When creating a new item, labels field is prepopulated and can't be cleared

### ISSUE THREAD

**Issue by don-ferris** [sysadminsmedia/homebox#181]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Where do I find that?

### What is the issue you are experiencing?

When creating a new item, the labels field is prepopulated with the labels from the last item created. If there's a way to clear the field or delete individual labels, I haven't found it.

### How can the maintainer reproduce the issue?

Create an item. Give it some labels. Save it and create a new item. Look at the labels field.

### Deployment

Docker (Linux)

**Comment by Millio345** [comment]
I always thought this was an intentional feature to allow quickly creating multiple items with the same labels, a bit like pre-filling the location when adding an item from a location view. You can clear the label by selecting it again in the label list (it will have a green line in front of it to indicate it's selected).

It also seems to stop happening if you refresh the page after adding the first item.

**Comment by tankerkiller125** [comment]
They should carry over, but it should also be possible to remove them without a refresh.
