### ISSUE TITLE
Maintenance notifications/ calendar

### ISSUE THREAD

**Issue by petruut** [sysadminsmedia/homebox#190]
### What is the problem you are trying to solve with this feature?

Right now, I can't see an easy way to see a consolidated view of upcoming maintenance (or ways of sending notifications about this e.g. via a telegram bot).

### What is the solution you are proposing?

Either a notification centre to push/ surface upcoming maintenance, or a maintenance calendar. Ideally with some degree of integration with telegram/ calendar apps/ etc.

I love your app!

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by mcarbonne** [comment]
I agree, being able to see upcoming maintenances is a must have.
I drafted what I had in mind, a simple table like that covers most use cases (I think):
![homebox-maintenance-view](https://github.com/user-attachments/assets/5a49290c-e1d5-41a0-a1a5-ce01517001bd)
This page would be reachable from the menu:
![homebox-maintenance-menu](https://github.com/user-attachments/assets/80de5b99-ccd0-4026-8691-2ca96b2c642b)



Regarding notifications, rather than implementing specific providers, an alternative would be to use a library, such as https://github.com/containrrr/shoutrrr for instance.

**Comment by tankerkiller125** [comment]
Shoutrrr is already built in (Notifiers) so should be reusable.

**Comment by fcastilloec** [comment]
I know that the "Maintenance" view is already done, but this is the only issue also mentioning (tracking?) notifications. Should another issue be open just to track notifications?
@tankerkiller125 you mention "Nofifiers", is that already implemented in a release? How can we use it?

**Comment by tankerkiller125** [comment]
@fcastilloec It's in the profile page, you can setup notifications for upcoming Maintenace from there. See the services section of shoutrrr https://containrrr.dev/shoutrrr/v0.8/services/bark/ for details on the URL format to use for various services.
