### ISSUE TITLE
Broswer cache clears and language will match alphabetically with browser.

### ISSUE THREAD

**Issue by shielnic** [sysadminsmedia/homebox#404]
As stated in the discord chat:
"tankerkiller125 — Today at 12:59 PM
It uses the first language that matches from the browser languages list.

that1nick — Today at 1:00 PM
and why would it change the theme to a random one than the one I had set

tankerkiller125 — Today at 1:01 PM
If you clear all settings (Cookies, localStorage, etc.) it will clear all personal preferences (they are not saved to the database at the moment)
Ctrl + F5 should only clear the resource cache
If you run navigator.languages in the browser dev console it should spit out the list of languages that are being used to determine a default.

that1nick — Today at 1:03 PM
Image
should be that english is first
every now and then it also falls back to german when using my app on my phone but that one is pretty rare

tankerkiller125 — Today at 1:06 PM
Ah I see, the code doesn't pick the first in the list from the browser, it picks the first that matches alphabetically. Will have to look into that "

**Comment by tankerkiller125** [comment]
So I was actually wrong on this, turns out, it's working exactly as it should and is returning in the correct order. The issue is that there is no en-US language, nor de-DE language, which means that it falls onto the last to, which your browser is sending as `de`, `en`.

So there isn't actually anything we can fix here. It's just a simple issue of the order in which the browser sends the languages.
