### ISSUE TITLE
Multi-line description breaks exports

### ISSUE THREAD

**Issue by tankerkiller125** [sysadminsmedia/homebox#5]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.3

### What is the issue you are experiencing?

Multiline descriptions breaks the export file.

Originally reported by @Saturo78 in hay-kot/homebox#914

### How can the maintainer reproduce the issue?

Use a multi-line description and then export the file.

### Deployment

Docker (Linux)

**Comment by icanc0** [comment]
Can someone assign me to this? seems like a relatively trivial fix

**Comment by icanc0** [comment]
I can't reproduce this issue here. 

![image](https://github.com/sysadminsmedia/homebox/assets/44480394/8bac5f63-6880-4a0b-bb41-46fa6e0f4874)
![image](https://github.com/sysadminsmedia/homebox/assets/44480394/7a0baa63-2fc0-4f8a-937f-926a8dac106f)

The item exports and imports just fine. 

![image](https://github.com/sysadminsmedia/homebox/assets/44480394/c27d5b19-b049-4b32-b035-7a80ce0f7d93)
![image](https://github.com/sysadminsmedia/homebox/assets/44480394/15640347-c2c8-4906-aa0d-ab9ea1982984)

Both TSV/CSV imports are fine in Google Sheets. 

![image](https://github.com/sysadminsmedia/homebox/assets/44480394/0c88d4d9-1ff5-4ac0-8a8e-e3c10511a880)
Works fine with Excel Web too... Although it only accepts CSV. 

I'm 99% certain that this issue is fixed by giving the file the correct extension, as described as in #3.

**Comment by icanc0** [comment]
We can close this after #54 is merged, seems like the TSV/CSV confusion caused the bug.

**Comment by tankerkiller125** [comment]
#54 has been merged, and I also can no longer replicate this issue with the latest version of master with the patches.
