### ISSUE TITLE
Add an administration panel

### ISSUE THREAD

**Issue by nobodyspecial** [sysadminsmedia/homebox#63]
### What is the problem you are trying to solve with this feature?

There needs to be an admin user that can add new accounts and set permissions for those users.

### What is the solution you are proposing?

An administration panel that deals with users, permissions, and any other back-end settings.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by icanc0** [comment]
From the old repo:

https://github.com/hay-kot/homebox/issues/687
https://github.com/hay-kot/homebox/issues/19

Kinda agree with Hayden here, he proposed to have a CLI interface to reset passwords and do other operations, which is enough for a home usage scenario.

**Comment by katosdev** [comment]
Opening up for community feedback.

**Comment by ELind77** [comment]
As a very new user, password resets and new user onboarding flows are definitely pain points.  Seeing Hayden's comments on the old issues suggests that a full UI-based admin panel with user roles would be a major undertaking.  But a CLI/script on the back end that I could run by getting a shell in the container seems like a fine idea.

**Comment by mandopatriot** [comment]
Admin functions are always needed when providing access to others. Preference is a web GUI, but anything to start would be helpful.

**Comment by katosdev** [comment]
It has been agreed that due to the substantial requirements of a potential refactor in order to make this possible, for now we will instead focus efforts on the integration of OIDC (#6) and configuration of SSPR. Ideally, from a security perspective the reset of a password should fall with the end user and not with the administrator, as rightly mentioned by @hay-kot on Discord. 

With this in mind, I will close this for now but we've added to an internal backlog to potentially revisit down the line.
