### ISSUE TITLE
Feature Request: Publish on Dockerhub

### ISSUE THREAD

**Issue by MiranoVerhoef** [sysadminsmedia/homebox#99]
Hey,

Foremost thank you for continuing this amazing project.

I am using Synology Container to run my dockers, but I can't seem to find your (new) version of Homebox.

It searches the website: https://registry.hub.docker.com.

Could this version of HomeBox be uploaded there?

**Comment by tankerkiller125** [comment]
We only currently publish to the Github Container Registry, we'll have to dig into the docker hub registry terms and what not to make sure that they're acceptable. Especially since Docker pulled that stupid stunt last year regarding pricing and what not for uploading images and then walking it back after for certain projects.

**Comment by MiranoVerhoef** [comment]
> We only currently publish to the Github Container Registry, we'll have to dig into the docker hub registry terms and what not to make sure that they're acceptable. Especially since Docker pulled that stupid stunt last year regarding pricing and what not for uploading images and then walking it back after for certain projects.

Perfect! Meanwhile Synology users:

1. Enable SSH service on Synology
2. SSH into Synology
3. sudo su
4. docker pull ghcr.io/sysadminsmedia/homebox:latest

It will then pull up in Container manager. This works great for now :)

**Comment by MiranoVerhoef** [comment]
> > We only currently publish to the Github Container Registry, we'll have to dig into the docker hub registry terms and what not to make sure that they're acceptable. Especially since Docker pulled that stupid stunt last year regarding pricing and what not for uploading images and then walking it back after for certain projects.
> 
> Perfect! Meanwhile Synology users:
> 
> 1. Enable SSH service on Synology
> 2. SSH into Synology
> 3. sudo su
> 4. docker pull ghcr.io/sysadminsmedia/homebox:latest
> 
> It will then pull up in Container manager. This works great for now :)

Also found a "middleman" Docker which fixes the HTTP api's Github Container Registry is not using which breaks compatibility with Synology Container manager:

https://williamdurand.fr/2023/03/18/github-container-registry-proxy-and-synology/

**Comment by katosdev** [comment]
Dockerhub seem to make publishing an image impossible following their recent pricing changes. Looking into this currently but looks like the free version doesn't support pushes from GH actions? 
Anyone have any experience with this who might be able to confirm please?

**Comment by tankerkiller125** [comment]
Due to changes within Docker Hub and the time required to invest into just getting an organization setup and running, let alone getting images uploaded we will not be moving forward with this.

As noted, there are work arounds to use the Github registry instead of Docker hub for devices that are (for some reason) hard coded to use it.

**Comment by katosdev** [comment]
Sorry - CC @MiranoVerhoef / @harrisony / @edmundo
